Rework logging operator CRD
kyma-project/community pull request #575
Opened 2021-07-09 15:30 UTC by chrkl

**Description**

Changes proposed in this pull request:

- Apply feedback to CRD

**Related issue(s)**

See also https://github.com/kyma-project/kyma/issues/11105

2021-07-09 15:33 UTC, a-thaler commented on internal/proposals/logs/dynamic-backend-configuration/custom-operator/dynamic-fluentbit-config.md
>  - Not all available plugins for filters and outputs can be configured by this operator (for example, `Lua`), because such plugins need certain files mounted into the container, which isn't possible.
Can be removed I guess?

2021-07-12 12:47 UTC, JeremyHarisch approved these changes

2021-07-13 12:29 UTC, NHingerl requested changes

2021-07-13 12:29 UTC, NHingerl commented on internal/proposals/logs/dynamic-backend-configuration/custom-operator/dynamic-fluentbit-config.md
> +To have a simple API, one `CRD` for Fluent Bit configuration is created. This CRD has a field which holds the status of the CR, called `Status`, as well as a struct of the type `LoggingConfigurationS
```suggestion
To have a simple API, one `CRD` for Fluent Bit configuration is created. This CRD has a field that holds the status of the CR, called `Status`, as well as a struct of the type `LoggingConfigurationSpec`, called `Spec`, holding a list of configuration sections, called `Sections`. Each `Section` has a `content` attribute that holds a raw Fluent Bit configuration section. A `Section` can have optional `Files` and an `Environment`. `Files` are mounted into the Fluent Bit pods and can be referenced in configurations, for example, in Lua filters. The environment is a list of Kubernetes secret references.
```

2021-07-13 12:31 UTC, NHingerl approved these changes

2021-07-13 12:37 UTC, merged